### ISSUE TITLE
502 Error 

### ISSUE THREAD

**Issue by Croebh** [haswellr/CritterDB#53]
I'm getting a 502 Error when visiting the website

**Comment by haswellr** [comment]
Looking into it. CPU usage seems to have jumped to 100% around 5am PST.

**Comment by haswellr** [comment]
This seems to be an attack. I was not able to resolve it immediately and will have to look more after my work day. Sorry for the inconvenience.

**Comment by haswellr** [comment]
Fixed! The attack was a false alarm. While there were a bunch of strange connections, after tightening up security the issue persisted. The real issue was that the replica set was not set in the URL when connecting to the database. I'm unsure how this just cropped up now after years on this database. Anyways, resolved.
