### ISSUE TITLE
Feature request: Publish bestiary for Avrae only

### ISSUE THREAD

**Issue by schnautzr** [haswellr/CritterDB#65]
Seems the majority of bestiaries are created simply for convenience of using Avrae lookups, and these include a lot of bestiaries that people are marking as "private use only". When publishing a bestiary, there ought to be an option for publishing it for Avrae instead of publishing it publicly. This would reduce the number of duplicate bestiaries as well as listings of bestiaries that aren't actually supposed to be free to use.

**Comment by haswellr** [comment]
A couple months back I added functionality to share a link to private bestiaries. While it is not exclusive to Avrae, I believe it satisfies this need. You can find it from the Share icon when looking at a bestiary. 

When I implemented private Bestiary sharing I asked Avrae to begin consuming bestiaries using those links rather than requiring public bestiaries. I am not sure if they have taken on that work yet or not. Please reach out to their team as I think finishing this is on Avrae now.

**Comment by mommothazaz123** [comment]
Avrae supports importing both link-shared bestiaries and published bestiaries using `!bestiary import`.

**Comment by haswellr** [comment]
Awesome, thanks Andrew. Is the default guidance for Avrae users to use link-shared bestiaries? (If not, I think that would be worth doing to avoid the published bestiary spam)

**Comment by mommothazaz123** [comment]
I updated the language in the Avrae help to clarify this a little: https://github.com/avrae/avrae/commit/7025dbc212f6f0c08f320da864dff85788f43c64
