### ISSUE TITLE
Cannot Log In

### ISSUE THREAD

**Issue by eiderman989** [haswellr/CritterDB#74]
If this is a bug or issue report, please follow the template below:

**Actual Behavior**:
 -  `What is the issue? *` Cannot log in, website reads 'invalid username'
 -  `What is the expected behavior?` User name is the same as it has been for 3+ years. Should allow log-in

**Additional Information**:
 -  `Browser Type: *` Google Chrome
 -  `Browser Version: *` 86.0.4240.75 
 -  `OS: *` Windows 10

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by jafmitch2** [comment]
I am seeing the same issues.

Actual Behavior:

- `What is the issue?`  Login button does not take me away from the login page.
-` What is the expected behavior?`  Login button logs me in to my account and lets me access the website.

Additional Information:
- `Browser Type:`  Google Chrome
- `OS:`  Windows 10

**Comment by eiderman989** [comment]
EDIT: It seems to be working for me now. Didn't do anything differently.

**Comment by haswellr** [comment]
CritterDB has been seeing these outages over the past couple of weeks. I am still working on a fix. Sorry for the inconveniences, but it is back up and running now.
