### ISSUE TITLE
Alignment-Type Capitalization Bug

### ISSUE THREAD

**Issue by Siravia** [haswellr/CritterDB#90]
If this is a bug or issue report, please follow the template below:

**Actual Behavior**:
 -  `What is the issue? *` Most words in the alignment-type row are capitalized, but subtypes like Fiend (demon), and Chaotic evil have the second words begin as lowercase. Seems to be a similar issue to the bug that plagued Languages for a while. Also, monster stat blocks currently have small modifications available to their alignment - "Typically Lawful Good", no alignment given, "50% Lawful Evil, 50% Lawful Neutral" - not possible with the current format.
 -  `What is the expected behavior?` The entire alignment-type row is capitalized and can be modified directly (ie. "Gargantuan Dragon (Gem), Typically Lawful Neutral" vs "Gargantuan Dragon (gem), Lawful neutral").

**Additional Information**:
 -  `Browser Type: *` Chrome
 -  `Browser Version: *` Version 96.0.4664.110 (Official Build) (64-bit)
 -  `OS: *` Windows 10

**Comment by haswellr** [comment]
https://github.com/haswellr/CritterDB/commit/f8524951f8917d0813d6b3d79d637f42f743fedb and https://github.com/haswellr/CritterDB/commit/6abe53a8a09c76787c0dfc18e58ac5521c7390c9 correct the capitalization, https://github.com/haswellr/CritterDB/commit/74a98754e9bb43157e7f999cb53008b831a9bf66 makes alignment an open field with autofill, instead of a dropdown.
